Update optimized_img2img.py
optimized_img2img.py:10:1: 'torchvision.utils.make_grid' imported but unused
optimized_img2img.py:14:1: 'contextlib.contextmanager' imported but unused
optimized_img2img.py:15:1: redefinition of unused 'rearrange' from line 9
optimized_img2img.py:19:1: 'pandas as pd' imported but unused